const
    AndroidCpuFeatures       = '/usr/lib/libcpufeatures.a';
    AndroidIlmImf            = '/usr/lib/libIlmImf.a';
    AndroidIPPICV            = '/usr/lib/libippicv.a';
    AndroidBittNotify        = '/usr/lib/libittnotify.a';
    AndroidJasper            = '/usr/lib/libjasper.a';
    AndroidJpegTurbo         = '/usr/lib/libjpeg-turbo.a';
    AndroidPNG               = '/usr/lib/libpng.a';
    AndroidProtoBuf          = '/usr/lib/libprotobuf.a';
    AndroidTiff              = '/usr/lib/libtiff.a';
    AndroidWebP              = '/usr/lib/libwebp.a';
    AndroidQuirc             = '/usr/lib/libquirc.a';
    AndroidTbb               = '/usr/lib/libtbb.a';
    AndroidTegraHal          = '/usr/lib/libtegra_hal.a';